import React from 'react';
import Head from "next/head";
import styled from 'styled-components';
import Link from "next/link";


const Header = styled.div`
display: flex;
align-items:center;
justify-content:space-around;
width:100%;
height: 60px;
border-bottom: 2px solid #877ae6;
`

const NavLink = styled.a`
font-size:20px;
color:#5757d8;
cursor: pointer;
&:hover {
  color: blue;
  text-decoration:underline;
}

`
const Main = styled.main`
width:100%;
padding:20px;
`


const Layout: React.FC = ({children}) => {
    return (
        <>
            <Head>
                <title>Develops Today</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header >
            <Link href='/'>
                <NavLink>Latest Posts</NavLink>
            </Link>
            <Link href="/posts/new" >
                <NavLink>Create new post</NavLink>
            </Link>
            </Header>
            <Main >
                {children}
            </Main>
        </>
    );
};

export default Layout;